# Site settings
title: Casie Mattrisch
email: casiemattrisch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A budding UX/UI Designer's developmental outlet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cczapski.github.io.com" # the base hostname & protocol for your site
twitter_username: CAMattrisch
github_username:  cczapski

# Build settings
markdown: kramdown

# Pagination
paginate: 1
paginate_path: "/blog/page:num/"
