# Site settings
title: Casie's Awesome and Exciting Website
email: casieczapski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A budding UI Designer's developmental oulet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cczapski.github.io.com" # the base hostname & protocol for your site
twitter_username: casczap
github_username:  cczapski

# Build settings
markdown: kramdown
